spring:
    profiles.active: prod
    jpa:
        hibernate.ddl-auto: update
        properties.hibernate:
            jdbc.batch_size: 1000
            order_inserts: true
            order_updates: true

keycloak:
    realm: GW2TP
    resource: spring-boot
    bearer-only: true
    auth-server-url: https://auth.nimeji.com/
