spring:
  datasource:
    url: jdbc:h2:file:./data/test
    username: admin
    password: admin
    driver: org.h2.Driver
  jpa:
    properties.hibernate:
      generate_statistics: true
      session:
        events:
          log:
            LOG_QUERIES_SLOWER_THAN_MS: 1
  hikari:
    data-source-properties:
      cachePrepStmts: true
      useServerPrepStmts: true
      rewriteBatchedStatements: true
logging:
  level:
    org:
      hibernate:
        stat: DEBUG
        #SQL: DEBUG
        #cache: DEBUG