apiVersion: v1
kind: Service
metadata:
  name: gw2tp-db-service
spec:
  ports:
    - port: 80
  selector:
    app: gw2tp
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gw2tp-app
spec:
  selector:
    matchLabels:
      app: gw2tp
  replicas: 1
  template:
    metadata:
      labels:
        app: gw2tp
    spec:
      containers:
        - image: ghcr.io/nimeji/gw2tp:latest
          name: gw2tp-app
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: gw2tp
                  key: DB_URL
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: gw2tp
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: gw2tp
                  key: DB_PASS
          ports:
            - containerPort: 80
              name: gw2tp-app
