apiVersion: v1
kind: PersistentVolume
metadata:
  name: gw2tp-db-pv-volume
  labels:
    type: local
    app: gw2tp
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gw2tp-db-pv-claim
  labels:
    app: gw2tp
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi